{% set name = "fugue-sql-antlr" %}
{% set version = "0.2.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/fugue-project/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 42701c3da50b519295580bbd6f8be7c6117b909337e1c9a29ccf3d00337ca99f

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - antlr4-python3-runtime >=4.13.2,<4.14
    - jinja2
    - triad >=0.6.8
    - packaging
  run_constrained:
    - fugue-sql-antlr-cpp =={{ version }}

test:
  imports:
    - fugue_sql_antlr
    - fugue_sql_antlr_version
    - fugue_sql_antlr._parser.fugue_sqlParser
    - fugue_sql_antlr._parser.fugue_sqlVisitor
    - fugue_sql_antlr._parser.sa_fugue_sql
    - fugue_sql_antlr.constants
    - fugue_sql_antlr.parser
    - fugue_sql_antlr.visitor
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Cannot call any upstream tests because of the following errors:
    # E   ModuleNotFoundError: No module named 'speedy_antlr_tool'
    # ValueError: CPP parser is not installed, use 'auto' or 'py' as parse_mode

about:
  home: https://github.com/fugue-project/fugue-sql-antlr
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Fugue SQL Antlr Parser
  description: Fugue SQL Antlr Parser
  dev_url: https://github.com/fugue-project/fugue-sql-antlr
  doc_url: https://github.com/fugue-project/fugue-sql-antlr/blob/master/README.md

extra:
  recipe-maintainers:
    - charlesbluca
    - kvnkho
    - goodwanghan
    - thewchan
