{% set name = "fugue-sql-antlr" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fugue-sql-antlr-{{ version }}.tar.gz
  sha256: c5500be5d359de4f45a25f4f7aabc1e15e78fc07e2e7a55eaed246ff3941aaf4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - antlr4-python3-runtime >=4.10
    - jinja2
    - python >=3.6
    - triad

test:
  imports:
    - fugue_sql_antlr
    - fugue_sql_antlr_version
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fugue-project/fugue-sql-antlr
  summary: Fugue SQL Antlr Parser
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - charlesbluca
    - kvnkho
    - goodwanghan
    - thewchan
